import React, { useState, useEffect } from 'react';
import { Download, Calendar, Briefcase, User, Building, FileText, ChevronRight } from 'lucide-react';
import { getSalariesByStaff } from '../../api/index';
import './StaffPayroll.css';

const StaffPayroll = () => {
  const [payrollHistory, setPayrollHistory] = useState([]);
  const [selectedPayroll, setSelectedPayroll] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchPayroll();
  }, []);

  const fetchPayroll = async () => {
    try {
      setLoading(true);
      const session = JSON.parse(sessionStorage.getItem('staff_session') || '{}');
      // If referenceId is missing, fallback to hardcoded ID for demo robustness
      const staffId = session.referenceId || 'STF003'; 
      
      const res = await getSalariesByStaff(staffId);
      if (res.data && res.data.length > 0) {
        setPayrollHistory(res.data);
        setSelectedPayroll(res.data[0]);
      } else {
        setPayrollHistory([]);
        setSelectedPayroll(null);
      }
    } catch (err) {
      console.error('Failed to fetch payroll:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = () => {
    window.print();
  };

  if (loading) {
    return <div className="payroll-loading">Loading Payroll Data...</div>;
  }

  if (payrollHistory.length === 0 || !selectedPayroll) {
    return (
      <div className="payroll-container">
        <div className="payroll-header">
          <div>
            <h1 className="payroll-title">Payroll Details</h1>
            <p className="payroll-subtitle">View and download your monthly payslip</p>
          </div>
        </div>
        <div className="payslip-card" style={{ textAlign: 'center', padding: '4rem 2rem' }}>
          <h2 style={{ color: 'var(--text-muted)' }}>No Payroll Records Found</h2>
          <p style={{ marginTop: '0.5rem' }}>Your salary slips will appear here once generated by the Accounts department.</p>
        </div>
      </div>
    );
  }

  // Calculate generic + attendance deductions
  const basic = selectedPayroll.basicPay || 0;
  const working = selectedPayroll.workingDays || 30;
  const present = selectedPayroll.presentDays || 30;
  const attendanceDeduction = working > 0 ? (basic * ((working - present) / working)) : 0;
  const totalEarnings = basic + (selectedPayroll.hra || 0) + (selectedPayroll.medicalAllowance || 0) + (selectedPayroll.specialAllowance || 0);
  const totalDeductions = (selectedPayroll.deductions || 0) + attendanceDeduction;

  return (
    <div className="payroll-container">
      <div className="payroll-header">
        <div>
          <h1 className="payroll-title">Payroll Details</h1>
          <p className="payroll-subtitle">View and download your monthly payslip</p>
        </div>
        <button className="download-btn" onClick={handleDownload}>
          <Download size={18} />
          <span>Download Payslip</span>
        </button>
      </div>

      <div className="payroll-layout">
        {/* Sidebar: Salary History */}
        <div className="salary-history-sidebar no-print">
          <h3 className="history-title">Salary History</h3>
          <div className="history-list">
            {payrollHistory.map((record) => (
              <div 
                key={record._id} 
                className={`history-item ${selectedPayroll._id === record._id ? 'active' : ''}`}
                onClick={() => setSelectedPayroll(record)}
              >
                <div className="history-info">
                  <span className="history-month"><Calendar size={14}/> {record.billingMonth}</span>
                  <span className="history-status" style={{ color: record.status === 'Disbursed' ? '#10b981' : '#f59e0b' }}>
                    {record.status}
                  </span>
                </div>
                <div className="history-amount">
                  <span>₹{record.netSalary.toLocaleString()}</span>
                  <ChevronRight size={16} className="chevron" />
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Main Content: Payslip PDF View */}
        <div className="payslip-card" id="payslip-print-area">
          <div className="payslip-header">
            <div className="company-info">
              <h2>Apex College ERP</h2>
              <p>Payslip for the month of {selectedPayroll.billingMonth}</p>
            </div>
          </div>

          <div className="employee-details-grid">
            <div className="detail-item">
              <User className="detail-icon" size={16} />
              <div>
                <label>Employee Name</label>
                <p>{selectedPayroll.staffName}</p>
              </div>
            </div>
            <div className="detail-item">
              <Briefcase className="detail-icon" size={16} />
              <div>
                <label>Employee ID</label>
                <p>{selectedPayroll.staffId}</p>
              </div>
            </div>
            <div className="detail-item">
              <Building className="detail-icon" size={16} />
              <div>
                <label>Department</label>
                <p>{selectedPayroll.department}</p>
              </div>
            </div>
            <div className="detail-item">
              <FileText className="detail-icon" size={16} />
              <div>
                <label>Designation</label>
                <p>{selectedPayroll.designation}</p>
              </div>
            </div>
            <div className="detail-item">
              <Calendar className="detail-icon" size={16} />
              <div>
                <label>Working Days</label>
                <p>{selectedPayroll.workingDays} / {selectedPayroll.presentDays} Present</p>
              </div>
            </div>
          </div>

          <div className="salary-breakdown">
            <div className="earnings-section">
              <h3>Earnings</h3>
              <div className="breakdown-row">
                <span>Basic Pay</span>
                <span>₹{(selectedPayroll.basicPay || 0).toLocaleString()}</span>
              </div>
              <div className="breakdown-row">
                <span>House Rent Allowance (HRA)</span>
                <span>₹{(selectedPayroll.hra || 0).toLocaleString()}</span>
              </div>
              <div className="breakdown-row">
                <span>Medical Allowance</span>
                <span>₹{(selectedPayroll.medicalAllowance || 0).toLocaleString()}</span>
              </div>
              <div className="breakdown-row">
                <span>Special Allowance</span>
                <span>₹{(selectedPayroll.specialAllowance || 0).toLocaleString()}</span>
              </div>
              <div className="breakdown-row total-row">
                <span>Total Earnings</span>
                <span>₹{totalEarnings.toLocaleString()}</span>
              </div>
            </div>

            <div className="deductions-section">
              <h3>Deductions</h3>
              <div className="breakdown-row">
                <span>Attendance Deductions</span>
                <span>₹{Math.round(attendanceDeduction).toLocaleString()}</span>
              </div>
              <div className="breakdown-row">
                <span>Other Deductions (Tax, PF)</span>
                <span>₹{(selectedPayroll.deductions || 0).toLocaleString()}</span>
              </div>
              <div className="breakdown-row total-row">
                <span>Total Deductions</span>
                <span>₹{Math.round(totalDeductions).toLocaleString()}</span>
              </div>
            </div>
          </div>

          <div className="net-salary-section">
            <div className="net-salary-content">
              <h3>Net Salary Payable</h3>
              <p className="net-amount">₹{(selectedPayroll.netSalary || 0).toLocaleString()}</p>
              <p className="amount-words" style={{ fontSize: '13px' }}>
                Status: {selectedPayroll.status} {selectedPayroll.status === 'Disbursed' && `(Paid on ${new Date(selectedPayroll.paymentDate).toLocaleDateString()})`}
              </p>
            </div>
            <div className="signature-area">
              <div className="signature-line"></div>
              <p>Accounts Officer</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default StaffPayroll;
